### ISSUE TITLE
Develop and document debugging tools and procedures for lighthouse

### ISSUE THREAD

**Issue by heyimShivam** [oppia/oppia-web-developer-docs#126]
debugging instructions is not present in the wiki for lighthouse test failures

Link: [https://github.com/oppia/oppia/wiki/Lighthouse-Tests#debugging-lighthouse-tests](https://github.com/oppia/oppia/wiki/Lighthouse-Tests#debugging-lighthouse-tests)

**Comment by U8NWXD** [comment]
@heyimShivam do you mean that we don't have debugging instructions, or that there's no link to the debugging doc template?

**Comment by heyimShivam** [comment]
Yes instructions are not present

**Comment by U8NWXD** [comment]
OK, I've updated the issue title. Right now we don't have any such instructions because we haven't had to debug many lighthouse flakes, so this can be the issue for figuring those out. E2E flakes are causing the most issues right now, so it'll probably be a while before we get to the two lighthouse flakes we're seeing right now. If you want to figure out how to debug lighthouse flakes and document your process, I'd love to hear what you figure out!

**Comment by gp201** [comment]
This issue is more of a bug since; currently, there are no debugging tools supported by us.
