### ISSUE TITLE
Add solution for subprocess.CalledProcessError in troubleshooting docs

### ISSUE THREAD

**Issue by HardikGoyal2003** [oppia/oppia-web-developer-docs#299]
``subprocess.CalledProcessError: Command '['yarn', 'install', '--pure-lockfile']' returned non-zero exit status 1``

This issue is faced by many people, and a proposed solution is provided in this [comment](https://github.com/oppia/oppia/discussions/16983#discussioncomment-8610303). It has been confirmed with one of the folks this solution works for them in [this](https://github.com/oppia/oppia/discussions/20110) discussion.

So, we need to add this to troubleshooting docs so that future folks can easily find the solution.

**Comment by U8NWXD** [comment]
Note that this particular error message just indicates a failure by the `yarn install --pure-lockfile` command. There are many possible reasons for this command execution to fail, for example a network interruption or `yarn` not being available, both of which were faced by contributors on the discussion linked-to above or related threads. A more specific error message farther up in the output should show what caused `yarn install ...` to fail, and this is the error message we should probably be designing solutions for.

I'd recommend adding a troubleshooting guide entry that mentions `subprocess.CalledProcessError: Command '['yarn', 'install', '--pure-lockfile']' returned non-zero exit status 1` since that seems to be what people latch on to. Then explain that we need to look farther up in the log for the more specific error message. Finally, list solutions along with the associated specific error messages. That way someone with a network failure doesn't try the solution for a missing `yarn` executable.

**Comment by HardikGoyal2003** [comment]
> Note that this particular error message just indicates a failure by the `yarn install --pure-lockfile` command. There are many possible reasons for this command execution to fail, for example a network interruption or `yarn` not being available, both of which were faced by contributors on the discussion linked-to above or related threads. A more specific error message farther up in the output should show what caused `yarn install ...` to fail, and this is the error message we should probably be designing solutions for.
> 
> I'd recommend adding a troubleshooting guide entry that mentions `subprocess.CalledProcessError: Command '['yarn', 'install', '--pure-lockfile']' returned non-zero exit status 1` since that seems to be what people latch on to. Then explain that we need to look farther up in the log for the more specific error message. Finally, list solutions along with the associated specific error messages. That way someone with a network failure doesn't try the solution for a missing `yarn` executable.

@U8NWXD We have not received confirmation regarding the resolution of the network error by the folks who were facing this error. If you agree, I can mark [this](https://github.com/oppia/oppia/discussions/17453#discussioncomment-5102684) as a solution and reflect the update in the documentation! Thank you!

**Comment by U8NWXD** [comment]
No, I wouldn't mark it as the solution until we get confirmation that it works. I propose listing only confirmed solutions in the troubleshooting page, though you could still list error messages for which we don't have solutions along with speculation about what we think might be going wrong

**Comment by HardikGoyal2003** [comment]
@U8NWXD I feel mentioning all the error messages and their speculation in the troubleshooting page can be a bit confusing for the folks who are facing it as speculation is a probability not any confirmed solution. WDYT?

**Comment by U8NWXD** [comment]
I'm fine with leaving out the unconfirmed solutions
