### ISSUE TITLE
Wiki page with “how to triage issues” instructions 

### ISSUE THREAD

**Issue by kevintab95** [oppia/oppia-web-developer-docs#58]
It is unclear how to triage issues that have the label "triage needed" in the web repo. It would be a nice to have clear set of instructions on the wiki so future triagers can follow that to correctly triage issues.

**Comment by U8NWXD** [comment]
What kind of instructions are you thinking of? Right now we just assign the issue based on what team's scope it falls under. Team scopes are described on the projects page. There's a fair amount of ambiguity though, which gets handled by Sean (who currently does the triage) making a judgement call

**Comment by seanlip** [comment]
Actually I think it's still worth having instructions so that this triage process can be spread out among multiple folks. It's fine if that list of instructions is short; we can link to it in the issue label's description on the labels page.

The instructions are indeed to just add the issue to a "project" based on what team's scope it falls under. I think the important part is perhaps to use that page for chronicling the ambiguous cases; personally when I do the triaging I feel it's pretty clear where things go but it would help me to know what other folks find ambiguous so I can add clarification to said page on an ongoing basis.

**Comment by gp201** [comment]
This was addressed by https://github.com/oppia/oppia-web-developer-docs/pull/51
