### ISSUE TITLE
Move all diagrams to mermaid

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#81]
Since GitHub now supports mermaid, we can move all diagrams that are present as images or in codeblocks to mermaid to allow developers to edit the diagrams in the codebase itself and allow users to comprehend the diagrams better.

Example: https://github.com/oppia/oppia-web-developer-docs/blob/dcce62e6f96a8312f9a14add54402565ae8164c5/Contributing-code-to-Oppia.md?plain=1#L91-L94

More info: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams

**Comment by deadex-ng** [comment]
@gp201 I'll work on this.

**Comment by gp201** [comment]
@deadex-ng I have assigned this issue to you.

**Comment by deadex-ng** [comment]
@gp201 - Before I proceed with moving the rest of the diagrams to mermaid, could you take a look at [these](https://github.com/deadex-ng/oppia-web-developer-docs/blob/fumba-mermaid/Apache-Beam-Jobs.md) mermaid diagrams. I haven't removed the original diagrams yet so that you can compare them.

**Comment by gp201** [comment]
@deadex-ng LGTM, you can proceed with the rest of the diagrams

**Comment by deadex-ng** [comment]
@gp201 - take a look at this [diagram](https://github.com/deadex-ng/oppia-web-developer-docs/blob/fumba-mermaid/End-to-End-Tests.md#what-is-a-flake). Mermaid doesn't support arrows that point to nothing and this is a challenge because some arrows in the original diagram point to nothing. 
In the meantime, I added random characters so the arrows should point to something: `O`,`o` and `.`  
I'm wondering how I can go about this challenge.

**Comment by deadex-ng** [comment]
@gp201  - These diagrams could not be moved to mermaid because of their complexity nature
-  [Diagram 1](https://github.com/oppia/oppia-web-developer-docs/blob/develop/End-to-End-Tests.md#what-is-a-flake)
- [Diagram 2](https://github.com/oppia/oppia-web-developer-docs/blob/develop/Extensions-Overview.md#documentation)
