### ISSUE TITLE
Remove Statement about node_modules in Linux Installation Guide

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#87]
The Linux installation guide says:

> **Note:** The script will create two folders that are siblings of the oppia/ root directory: oppia_tools and node_modules. This is done so that these two folders will not be uploaded to App Engine when the application is deployed to the web.

This is not true of `node_modules` anymore

**Comment by Patel-Muhammad** [comment]
### Hey @U8NWXD , can I take on this issue?
I will do the following:
1.  I will go to "Installing-Oppia-(Linux;-Python-3).md"
2. Remove the lines :    
**Note**: The script will create two folders that are siblings of the `oppia/` root directory: `oppia_tools` and `node_modules`. This is done so that these two folders will not be uploaded to App Engine when the application is deployed to the web.

**Comment by U8NWXD** [comment]
Two comments:

1. Instead of just removing that note, can you update it to make it correct?
2. Can you also fix this in the macOS installation instructions? Those instructions have the same note, so the same changes should work for both sets of instructions

**Comment by Patel-Muhammad** [comment]
### @U8NWXD  sure, I will do the following:

**1. I will remove the lines:** 
>Note: The script will create two folders that are siblings of the oppia/ root directory: oppia_tools and node_modules. This is done so that these two folders will not be uploaded to App Engine when the application is deployed to the web.

**2. I will add the following lines for [ linux installation](https://github.com/oppia/oppia-web-developer-docs/blob/develop/Installing-Oppia-(Linux%3B-Python-3).md) and [macOs installation](https://github.com/oppia/oppia-web-developer-docs/blob/develop/Installing-Oppia-(Mac-OS%3B-Python-3).md):**
>The script creates two folders that are siblings of the oppia/ root directory: oppia_tools and node_modules. This is done to prevent oppia_tools from being uploaded to App Engine when the application is deployed. However, it's worth noting that App Engine now automatically ignores the node_modules directory during deployment, so it is no longer necessary to create a separate folder for it.

**Comment by U8NWXD** [comment]
I don't think the lines you're planning to add are true. `node_modules` is a child of the `oppia/` directory, not a sibling. 

Also, there are some other folders that get created as siblings. Maybe we should mention those too?

**Comment by Patel-Muhammad** [comment]
@U8NWXD I am sorry, I don't exactly understand what the script will do, and what folders will be created where. Can you please explain it to me or point me to a resource?

**Comment by seanlip** [comment]
@Patel-Muhammad In order to tackle this issue successfully, you will probably need to actually read the script in question and understand what it does so that you can update the wiki page correctly. A key part of solving this issue (and most issues, actually) is doing the necessary investigation in order to figure out exactly what edits need to be made.

**Comment by Patel-Muhammad** [comment]
Thanks for the suggestion, I will make sure to read the script and update the wiki page accordingly.

**Comment by AKASH-PRASAD7** [comment]
Hello, I want to work on this issue.

**Comment by Patel-Muhammad** [comment]
Hey, I am working on another issue right now, maybe someone else can solve this issue.

**Comment by U8NWXD** [comment]
@AKASH-PRASAD7 please follow our instructions for taking up good first issues: https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue

**Comment by sasha-cz** [comment]
@U8NWXD Can I take this issue? 

 I would change the note within  "Installing-Oppia-(Linux;-Python-3).md" and in "Installing-Oppia-(Mac-OS;-Python-3).md" to the following: 

The script will create a number of files and folders that are siblings of the `oppia/` root directory (e.g. `oppia_tools`). This is done so that these files and folders will not be uploaded to App Engine when the application is deployed to the web.

**Comment by seanlip** [comment]
Go for it @sasha-cz, I've assigned you. Thanks!

**Comment by Ash-2k3** [comment]
Closing as completed in https://github.com/oppia/oppia-web-developer-docs/pull/200
